$computers = @'
ACHAMBLESS-LT
AGULLO-LT
ARANKINS-LT
BKIMES-LT
CCARROLL-LT
CREYNOLDS-LT
CRIDENHOUR-LT
CROUNDTREE-LT
CSPURLOCK-LT
CVANDYKE-LT
DBAKER-LT
DDIEHL-LT
DROBERTSON-LT
ECOHOON-LT
FRKUSANALPT1937
FRKUSANALPT2021
FRKUSANALPT2682
FRKUSANALPT6926
FRKUSANALPT8361
FRKUSANALPTGKR4
FRKUSANALPTHTL6
FRKUSANALPTLG0G
FRKUSANALPTSX9R
FRKUSANALPTTXT0
FRKUSANALPTXAX1
FRKUSANALPTZQOI
JALSTON-LT
JBENNER-LT
JJONES-LT
JLINK-LT
KHAYES-LT
KPIERSON-LT
LCHIMENTO-LT
LCRANE-LT
LPAREIGIS-LT
LRUSSO-LT
MHOLETON-LT
NEISCHEN-LT
RRAUSCH-LT
SKING-LT
SMARTINEZ-LT
TBISHIR-LT
'@ -split [environment]::NewLine

$ErrorActionPreference = 'Stop'

foreach ($comp in $computers.samaccountname) {
  try {
    $removeADComputerSplat = @{
      Verbose = $true
      WhatIf  = $true
    }

    Get-ADComputer -Identity $comp | Remove-ADComputer @removeADComputerSplat
    Write-Output "Removed Computer $($comp)"
  }
  catch {
    $Error.Message
  }
}