@startuml AzureMfa
if (Run Script) then (Success)
if (Connect to Azure) then (Success)
  :Get All Users;
  if (
    Is member of
  Az_OnPremOnly
      ) then (True)
    :Azure Mfa True;
    :Remove from Group;
    :Construct Objects;
    :User Count -;
    :Generate Removed Csv;
  else (False)
    :Azure Mfa False;
    :Add to Group;
    :Construct Objects;
    :User Count +;
    :Generate Added Csv;
  endif
    :Construct Email;
    :Attach Files;
    :Send Email;
else (Failed)
  #Red:Log Error;<
  stop
endif
  stop
else (Failed)
  #Red:Log Error;<
  stop
@enduml