$Computers =
@'
test's imac
thrd-dept-macpr
cgr-2934afreela
cgr-aboribo-mac
cgr-aowett-imac
cgr-aowett-mba1
cgr-bloo004-ima
cgr-caustopc-ma
cgr-cbatten-mbp
cgr-crai004-mac
cgr-csingh-imac
cgr-dbett-macpr
cgr-dclemen-ima
cgr-ddeguzma-im
cgr-dept-imac21
cgr-dept-imac27
cgr-dept-mbp15l
cgr-dtavarez-im
cgr-dtavarez-mb
cgr-eric006-mbp
cgr-eslovin-mbp
cgr-fchubach-im
cgr-fharkin-mac
cgr-fharkin-mbp
cgr-freelance-i
cgr-happ002-ima
cgr-jcheuse-mac
cgr-jgilli-macp
cgr-jgonzal-ima
cgr-john045-mba
cgr-mant028-mbp
cgr-mfoley-macp
cgr-mmarulan-ma
cgr-mmurphy-ima
cgr-mperez1-ima
cgr-perr016-ima
cgr-quer004-ima
cgr-ralcock-mac
cgr-rslimak-mac
cgr-sberlan-ima
cgr-sduncan-mbp
cgr-stol049-mac
cgr-tmorga1-ima
cmg-dsoler1-ima
cmg-svanhor-mbp
ist-amarti1-ima
ist-bfarley-ima
ist-dept-imac21
ist-dept-mbp15m
ist-domi011-ima
ist-duva004-ima
ist-ekalkst-ima
ist-fmetcal-ima
ist-jramos1-ima
ist-lgervas-ima
ist-rcapasso-im
ist-rdewilde-im
ist-rice06-mba1
ist-rirwin1-mbp
ist-ryaus-imac2
leg-ablock-mbpr
leg-dsalmier-mb
leg-duqu008-ima
leg-freelance-i
leg-gbrennis-im
leg-intern-imac
leg-jcohen1-ima
leg-jjackson-im
leg-jjames-imac
leg-jlane01-ima
leg-jraditc-ima
leg-ldelgre-ima
leg-salc007-mbp
leg-scwa176-mbp
leg-tmullen-mba
leg-tsmith-mbp1
leg-vcampan-mbp
leg-videdit-mac
mstwrk-lkszan-m
red-bsarull-mbp
red-diaz019-mbp
red-fdonato-mac
red-nlichte-mbp
red-rkordisc-mb
red-rwetsto-mbp
red-shlee-mbp15
bnx-w80181faagu
camc02hd10hdv10
camc02rm27hg8wl
col-anewton1-mb
col-hwerthe-mbp
col-igreen1-mbp
col-twalla2-mbp
epic-coul010-mb
epic-enve001-mb
epic-pres021-mb
epic-rama018-mb
exec-shor004-mb
gdb-jwalker-mba
mc02pw2jvg8wm
nash-jfox1-macp
nash-wats006-ma
rca-melbaz-mbpr
sycoanrmac
tor-cmannix-mbp
tor-imarcan2-mb
tor-mgamble-mbp
tor-tschiem-mbp
usmc02px2xdfvh8
usmd550003967
ussales-sumn004
usmc02mh28sfd58
usmc02p90lvg3qn
usmc02pw2jpg8wm
usmc02pw2kjg8wm
usmc02px1n4fvh8
usmc02px2hyfvh8
usmc02px2r4fvh8
usmc02px2ysfvh8
usmc02px2yvfvh8
usmc02px30cfvh8
usmc02px36hfvh8
usmc02q81t7g8wm
usmc02qh28cfvh8
usmc02rg1b1fvh8
usmc1mpj7mpg944
astro-chen393-m
usmc02ppakafvh5
'@ -split [environment]::NewLine

$targetOu = 'bmg.bagint.com/USA/GBL/GRP/Restricted/Disabled Computers/MAC'

foreach ($computer in $Computers){
  Disable-QADComputer -Identity $computer -whatif
  Move-QADObject -Identity $computer -To $targetOu -WhatIf
}